
export const ACTION_TYPE = {
    FETCH_GLOBAL_DATA : 'FETCH_GLOBAL_DATA',
    FETCH_ALL_COUNTRIES_NAME: 'FETCH_ALL_COUNTRIES_NAME',
    FETCH_COUNTRY_SUMMARY: 'FETCH_COUNTRY_SUMMARY',
    FETCH_COUNTRY_DETAILS: 'FETCH_COUNTRY_DETAILS',
    FETCH_ALL_COUNTRY_SUMMARY: 'FETCH_ALL_COUNTRY_SUMMARY'
}